CC = gcc-15
# CFLAGS = -fopenmp -O1
# CFLAGS = -fopenmp -O2
# CFLAGS = -fopenmp -O3
# CFLAGS = -fopenmp -Ofast
# CFLAGS = -fopenmp -O2 -march=native
# CFLAGS = -fopenmp -O3 -march=native
CFLAGS = -fopenmp -Ofast -march=native

TARGETS = slow medium fast

all: $(TARGETS)

slow: slow.c
	$(CC) $(CFLAGS) -o slow slow.c

medium: medium.c
	$(CC) $(CFLAGS) -o medium medium.c

fast: fast.c
	$(CC) $(CFLAGS) -o fast fast.c

clean:
	rm -f $(TARGETS)