.PHONY: all run analyze clean

all:
	$(MAKE) -C ex1
	$(MAKE) -C ex2
	$(MAKE) -C ex3

run:
	$(MAKE) -C ex1 run
	$(MAKE) -C ex2 run
	$(MAKE) -C ex3 run

analyze:
	$(MAKE) -C ex1 analyze
	$(MAKE) -C ex2 analyze
	$(MAKE) -C ex3 analyze

clean:
	$(MAKE) -C ex1 clean
	$(MAKE) -C ex2 clean
	$(MAKE) -C ex3 clean
