CFLAGS = -std=gnu11 -Wall -Werror -Wextra -fopenmp -O3

.PHONY: all
all: false_sharing false_sharing_2

.PHONY: clean
clean:
	$(RM) false_sharing false_sharing_2

false_sharing: false_sharing.c

false_sharing_2: false_sharing_2.c
